App_Admin/urls.py
from django.urls import path
from App_Admin import views

app_name = 'App_Admin'


urlpatterns = [
    path('', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-authentication/', views.admin_authentication_view, name='admin-authentication'),
    path('logout/', views.logout_view, name='logout'),
    path('products/', views.products_gallery, name='products'),
    path('running-auction/', views.running_auction, name='running-auction'),
    path('product-price-time-series/<product_key>/', views.product_price_time_series, name='product-price-time-series'),
    path('added-ended-chart-product/', views.added_ended_chart_product, name='added-ended-chart-product'),
    path('added-ended-chart/<pk>/', views.added_ended_chart, name='added-ended-chart'),
]

App_Auction/urls.py
from django.urls import path
from App_Auction import views

app_name = 'App_Auction'


urlpatterns = [
    path('product-details/<product_key>', views.product_details_view, name='product-details'),
    path('bid-request/', views.bid_start_view, name='bid-request'),
    path('user-participant-auction/', views.user_participant_auctions, name='user-participant-auction'),
    path('my-posted-auctions/', views.my_posted_auctions, name='my-posted-auctions'),
]

Maloy_Auction_BD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import App_Auction.views

urlpatterns = [
    path('super-admin/', admin.site.urls),
    path('', App_Auction.views.home_view, name='home'),
    path('auction/', include('App_Auction.urls')),
    path('accounts/', include('App_Authentication.urls')),
    path('admin/', include('App_Admin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Auction/models.py
import datetime

from django.db import models
from django_mysql.models import ListCharField

# Create your models here.
from App_Authentication.models import User

user_length = len(User.objects.all())


class ProductModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    new_bidder = models.CharField(max_length=100, blank=True, null=True)
    product_name = models.CharField(max_length=200)
    product_photo = models.ImageField(upload_to='product_image')
    minimum_bid_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField(blank=True, null=True)
    product_description = models.TextField()
    auction_end_date = models.DateField()
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now=True)


now = datetime.datetime.now()


class ProductLastPrices(models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name='product')
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    price = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)


# user input, Product Name, Product Description, Product Photo, Minimum Bid Price, and Auction End DateTime

App_Auction/forms.py
from django import forms
from App_Auction.models import ProductModel


class AuctionProductForm(forms.ModelForm):
    auction_end_date = forms.CharField(widget=forms.TextInput(
        attrs={'type': 'date'}))

    class Meta:
        model = ProductModel
        exclude = ['user', 'new_bidder', 'selling_price', 'status', 'created', ]

App_Auction/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from App_Auction.models import *
from App_Auction.forms import *


# Create your views here.
def is_customer(user):
    return user.groups.filter(name='CUSTOMER').exists()


@user_passes_test(is_customer)
def home_view(request):
    if not request.user.is_authenticated:
        return redirect('App_Authentication:authentication')
    products = ProductModel.objects.filter(status=True).order_by('-created')
    form = AuctionProductForm()
    if request.method == 'POST':
        form = AuctionProductForm(request.POST, request.FILES)
        if form.is_valid():
            minimum_price = request.POST.get('minimum_bid_price')
            form_save = form.save(commit=False)
            form_save.user = request.user
            form_save.status = True
            form_save.save()
            bid_price_list = ProductLastPrices(product_id=form_save.pk, price=minimum_price)
            bid_price_list.save()
            return redirect('home')
    content = {
        'products': products,
        'form': form
    }
    return render(request, 'home.html', context=content)


def product_details_view(request, product_key):
    product = ProductModel.objects.get(id=product_key)
    bidding_table = ProductLastPrices.objects.all().filter(product_id=product_key)
    bidder = False
    min_bid_price = product.minimum_bid_price
    try:
        bidder_exists = ProductLastPrices.objects.get(product=product, bidder=request.user)
        if bidder_exists:
            bidder = True
            min_bid_price = bidder_exists.price
    except:
        bidder = False

    # Date
    today = datetime.datetime.today().date()
    # Date End
    # Product Bidding Date Ended or not (Start)
    winner = None
    winner_one = None
    if product.auction_end_date < today:
        product.status = False
        max_price = max([i.price for i in bidding_table.order_by('date')])
        winner_list = [i for i in bidding_table if i.price == max_price]
        old_date = min([i.date for i in winner_list])
        winner = [i for i in winner_list if i.date == old_date]
        winner_one = winner[0].bidder

    # Product Bidding Date Ended or not (End)

    if not product.status:
        timeup = True
    else:
        timeup = False
    content = {
        'product': product,
        'bidding_table': bidding_table,
        'bidder_exist': bidder,
        'min_bid_price': min_bid_price,
        'timeup': timeup,
        'winner_one': winner_one
    }

    return render(request, 'App_Auction/product_details.html', context=content)


def bid_start_view(request):
    if request.method == 'POST':
        product_key = request.POST.get('product_key')
        bid_price = request.POST.get('bid_price')
        product = ProductModel.objects.get(id=product_key)
        if request.user == product.user:
            messages.error(request, "You are the auction owner, You can't bid")
            return HttpResponseRedirect(reverse('App_Auction:product-details', kwargs={'product_key': product_key}))
        try:
            bidder_exists = ProductLastPrices.objects.get(product=product, bidder=request.user)
            bidder_exists.price = bid_price
            bidder_exists.save()
        except:
            newBid = ProductLastPrices.objects.create(product=product, bidder=request.user, price=int(bid_price))
            newBid.save()
        return HttpResponseRedirect(reverse('App_Auction:product-details', kwargs={'product_key': product_key}))


def user_participant_auctions(request):
    user_part_auction = ProductLastPrices.objects.all().filter(bidder=request.user)
    content = {
        'user_part_auction': user_part_auction
    }
    return render(request, 'App_Auction/auction_bag.html', context=content)


def my_posted_auctions(request):
    my_posted_items = ProductModel.objects.all().filter(user=request.user)

    content = {
        'myposteditems': my_posted_items
    }
    return render(request, 'App_Auction/my_posted_items.html', context=content)

templates/App_Auction/auction_bag.html
{% extends 'base.html' %}
{% block title %}
    Participation
{% endblock %}
{% block main %}
    <style>
        /* Table Style Start */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        table caption {
            font-size: 1.5em;
            margin: .5em 0 .75em;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }

        /* Table Style End */
    </style>

    <div class="container">
        <table>
            <legend style="margin: 30px 0; padding: 15px; text-align: center">Auctions</legend>
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Product Name</th>
                <th scope="col">Bidding Price</th>
                <th scope="col">Update Price</th>
            </tr>
            </thead>
            <tbody>
            {% for auction in user_part_auction %}
                <tr>
                    <td data-label="Date">{{ auction.date }}</td>
                    <td data-label="Product Name">{{ auction.product.product_name }}</td>
                    <td data-label="Bidding Price">{{ auction.price }}</td>
                    <td data-label="Update Price">
                        <button class="btn btn-warning"
                                onclick="window.location.href='{% url "App_Auction:product-details" product_key=auction.product.id %}'">
                            Update
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/App_Auction/my_posted_items.html
{% extends 'base.html' %}
{% block title %}
    Participation
{% endblock %}
{% block main %}
    <style>
        /* Table Style Start */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        table caption {
            font-size: 1.5em;
            margin: .5em 0 .75em;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }

        /* Table Style End */
    </style>

    <div class="container">
        <table>
            <legend style="margin: 30px 0; padding: 15px; text-align: center">Auctions</legend>
            <thead>
            <tr>
                <th scope="col">Create Date</th>
                <th scope="col">Auction Ended Date</th>
                <th scope="col">Product Name</th>
                <th scope="col">Minimum Bidding Price</th>
                <th scope="col">Update Price</th>
            </tr>
            </thead>
            <tbody>
            {% for item in myposteditems %}
                <tr>
                    <td data-label="Create Date">{{ item.created }}</td>
                    <td data-label="Auction Ended Date">{{ item.auction_end_date }}</td>
                    <td data-label="Product Name">{{ item.product_name }}</td>
                    <td data-label="Minimum Bidding Price">{{ item.minimum_bid_price }}</td>
                    <td data-label="Update Price">
                        <button class="btn btn-warning"
                                onclick="window.location.href='{% url "App_Auction:product-details" product_key=item.id %}'">
                            Details
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/App_Auction/product_details.html
{% extends 'base.html' %}
{% block title %}
    {{ product.product_name }}
{% endblock %}
{% block main %}

    <style>
        ._product-details {
            padding: 60px;
            box-shadow: 0 0 5px #2c3034;
            -webkit-box-shadow: 0 0 5px #2c3034;
        }

        ._minimum-bidding-price {
            font-weight: bold;
            font-size: 16px;
            color: rgba(139, 0, 0, 0.89);
        }

        .startBtn {
            -webkit-box-shadow: 0 0 3px darkred;
            box-shadow: 0 0 3px darkred;
            background-color: darkred;
            color: #fff3cd;
        }

        .startBtn:hover {
            -webkit-box-shadow: 0 0 8px darkred;
            box-shadow: 0 0 8px darkred;
            background-color: darkred;
            color: #fff3cd;
        }

        /* Table Style Start */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        table caption {
            font-size: 1.5em;
            margin: .5em 0 .75em;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }

        /* Table Style End */
    </style>

    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                {% if messages %}
                    {% for message in messages %}
                        <h3 class="alert-warning text-center p-3 m-2 text-uppercase">{{ message }}</h3>
                    {% endfor %}

                {% endif %}
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>

    <div class="container">
        <div class="row p-3 m-3">
            <div class="col-md-6">
                <div class="p-3">
                    <img src="{{ product.product_photo.url }}" alt="Product Photo">
                </div>
            </div>
            <div class="col-md-6 _product-details">
                <div class="row">
                    <h3>{{ product.product_name }}</h3>
                    <hr>
                </div>
                <div class="row mt-5">
                    <p>
                        <span class="_minimum-bidding-price">
                            Minimum Bid Price: {{ product.minimum_bid_price }}
                        </span>
                    </p>
                    <p>
                        Auction End At: {{ product.auction_end_date }}
                    </p>
                </div>
                <div class="row mt-3">
                    {% if timeup %}
                        <h4 style="box-shadow: 0 0 10px #198754; -webkit-box-shadow: 0 0 10px #198754; padding: 10px; text-align: center">
                            <span class="text-danger">Winner</span>
                            <span class="text-success">{{ winner_one }}</span>
                        </h4>
                    {% else %}
                        <form method="post" class="form-group" action="{% url 'App_Auction:bid-request' %}">
                            {% csrf_token %}
                            <input type="number" value="{{ product.id }}" name="product_key" style="display: none">
                            <input type="number" min="{{ product.minimum_bid_price }}" name="bid_price"
                                   value="{{ min_bid_price }}"
                                   placeholder="Your Price" class="form-control">
                            <div class="form-group">
                                {% if bidder_exist %}
                                    <button class="btn mt-3 startBtn" type="submit">Update Bid</button>
                                {% else %}
                                    <button class="btn mt-3 startBtn" type="submit">Start Bidding</button>
                                {% endif %}
                            </div>
                        </form>
                    {% endif %}
                </div>
                <div class="row mt-5" style="cursor: none">
                    <h5 style="margin: 10px 0;">
                        <a style="text-decoration: #2c3034;">Description</a>
                    </h5>
                    <p>
                        {{ product.product_description|safe }}
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <table>
                <caption>Last Bidding Prices</caption>
                <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Bidder Name</th>
                    <th scope="col">Bidding Price</th>
                </tr>
                </thead>
                <tbody>
                {% for bid in bidding_table %}
                    {% if bid.bidder %}
                        <tr>
                            <td data-label="Date">{{ bid.date }}</td>
                            <td data-label="Product Name">{{ product.product_name }}</td>
                            <td data-label="Bidder Name">{{ bid.bidder }}</td>
                            <td data-label="Bidding Price">{{ bid.price }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}