App_Admin/urls.py
from django.urls import path
from App_Admin import views

app_name = 'App_Admin'


urlpatterns = [
    path('', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-authentication/', views.admin_authentication_view, name='admin-authentication'),
    path('logout/', views.logout_view, name='logout'),
    path('products/', views.products_gallery, name='products'),
    path('running-auction/', views.running_auction, name='running-auction'),
    path('product-price-time-series/<product_key>/', views.product_price_time_series, name='product-price-time-series'),
    path('added-ended-chart-product/', views.added_ended_chart_product, name='added-ended-chart-product'),
    path('added-ended-chart/<pk>/', views.added_ended_chart, name='added-ended-chart'),
]

Maloy_Auction_BD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import App_Auction.views

urlpatterns = [
    path('super-admin/', admin.site.urls),
    path('', App_Auction.views.home_view, name='home'),
    path('auction/', include('App_Auction.urls')),
    path('accounts/', include('App_Authentication.urls')),
    path('admin/', include('App_Admin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Admin/models.py
from django.db import models

# Create your models here.

App_Admin/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from App_Auction.models import *
from App_Authentication.models import User


# Create your views here.
def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()


@user_passes_test(is_admin)
def admin_dashboard_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('App_Admin:admin-authentication'))

    product_price = ProductLastPrices.objects.all()
    product = ProductModel.objects.filter(status=True)
    date = []
    price = []
    for i in product_price:
        date.append(f"{i.date.day}-{i.date.month}-{i.date.year}")
        price.append(i.price)

    content = {
        'product_price': product_price,
        'date': date,
        'price': price,
        'product': product,
    }
    return render(request, 'App_Admin/admin_dashboard.html', context=content)


def admin_authentication_view(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        user_email = request.POST.get('username')
        password = request.POST.get('password')
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=user_email, password=password)
            if user:
                login(request, user)
                if is_admin(user):
                    return HttpResponseRedirect(reverse('App_Admin:admin-dashboard'))
        else:
            form = User.objects.create(email=user_email)
            form.set_password(password)
            form.save()
            user = authenticate(username=user_email, password=password)
            admin_group = Group.objects.get_or_create(name='ADMIN')
            admin_group[0].user_set.add(user)
            if user:
                login(request, user)
                if is_admin(user):
                    return HttpResponseRedirect(reverse('App_Admin:admin-dashboard'))
    return render(request, 'App_Admin/Admin_authentication.html', context={'form': form})


def logout_view(request):
    logout(request)
    return redirect('App_Authentication:authentication')


def products_gallery(request):
    products = ProductModel.objects.filter(status=True)
    content = {
        'products': products
    }
    return render(request, 'App_Admin/products.html', context=content)


def running_auction(request):
    # Running Auction Statistics Start
    running_auctions = ProductModel.objects.filter(status=True)
    running_auctions_dict = {}
    for i in running_auctions:
        for j in i.product.values():
            try:
                running_auctions_dict[j['product_id']].append(j['price'])
            except KeyError:
                running_auctions_dict[j['product_id']] = ([j['price']])

    running_auctions_stat = {}
    for i, j in zip(running_auctions_dict.keys(), running_auctions_dict.values()):
        avg = sum(running_auctions_dict[i]) / len(running_auctions_dict[i])
        maximum = max(running_auctions_dict[i])
        minimum = min(running_auctions_dict[i])
        print(f"Avg: {avg}")
        print(f"Maximum: {maximum}")
        print(f"Minimum {minimum}")
        running_auctions_stat[i] = {'avg': avg, 'max': maximum, 'min': minimum}
    # Running Auction Statistics End

    content = {
        'running_auction': running_auctions,
        'running_auction_stat': zip(running_auctions_stat.keys(), running_auctions_stat.values()),
    }
    return render(request, 'App_Admin/running_auction.html', context=content)


def product_price_time_series(request, product_key):
    product_price = ProductLastPrices.objects.filter(product_id=product_key)
    price = []
    for i in product_price:
        price.append(i.price)
    content = {
        'product_price': product_price,
        'price': price
    }
    return render(request, 'App_Admin/product_price_time_series.html', context=content)


def added_ended_chart_product(request):
    product = ProductModel.objects.filter(status=True)
    content = {
        'product': product,
    }
    return render(request, 'App_Admin/added_ended_auction_chart_product.html', context=content)


def added_ended_chart(request, pk):
    product = ProductModel.objects.filter(status=True, id=pk)
    content = {
        'product': product
    }
    return render(request, 'App_Admin/added_and_ended_auction_chart.html', context=content)

templates/App_Admin/Admin_authentication.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    {% load crispy_forms_filters %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Login / Signup</title>
    <style>
        body {
            background: url("{% static 'images/login_background.jpg' %}") no-repeat center;
            background-size: cover;
        }

        form {
            padding: 30px;
            margin: 200px 0;
            box-shadow: 0 0 10px #081828;
            -webkit-box-shadow: 0 0 10px #081828;
            border-radius: 10px;
        }

        @media screen and (max-width: 320px) {
            form {
                padding: 25px;
                margin: 100px 0;
                box-shadow: 0 0 10px #081828;
                -webkit-box-shadow: 0 0 10px #081828;
                border-radius: 10px;
            }
        }

        @media screen and (max-width: 425px) {
            form {
                padding: 26px;
                margin: 100px 0;
                box-shadow: 0 0 10px #081828;
                -webkit-box-shadow: 0 0 10px #081828;
                border-radius: 10px;
            }
        }

        @media screen and (max-width: 768px) {
            form {
                padding: 28px;
                margin: 150px 0;
                box-shadow: 0 0 10px #081828;
                -webkit-box-shadow: 0 0 10px #081828;
                border-radius: 10px;
            }
        }

        legend {
            background-color: #081828 !important;
            color: #fff3cd;
            text-align: center;
            margin: 10px 0;
            padding: 15px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form method="post" class="form-group">
                {% csrf_token %}
                <legend class="form-group">Login / Signup Form</legend>
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group mt-2 mb-2">
                    <i class="fa fa-eye-slash field-icon"
                       style="color: wheat; background-color: #2c3034; float:right; padding: 5px"
                       onclick="showPassword()" id="id-showpass">
                        Show Password
                    </i>
                </div>
                <div class="form-group">
                    <button class="btn btn-success">Login/Signup</button>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<script>
    let showpass = document.getElementById('id-showpass');
    let id_password = document.getElementById('id_password');
    let id_email = document.getElementById('id_username');

    id_password.type = 'password';
    id_email.placeholder = "Email (ex. abcdefg@gmail.com)";
    id_password.placeholder = "Password";

    function showPassword() {
        if (id_password.type === 'password') {
            id_password.type = 'text';
            showpass.classList.add('fa-eye');
            showpass.classList.remove('fa-eye-slash');
            showpass.innerText = " Hide Password";
        } else {
            id_password.type = 'password';
            showpass.classList.add('fa-eye-slash');
            showpass.classList.remove('fa-eye');
            showpass.innerText = " Show Password";
        }
    }
</script>

</body>
</html>

templates/App_Admin/Admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Auction BD |
        {% block title %}
        {% endblock %}
    </title>
    <!-- bootstrap 5 css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/>
    <!-- BOX ICONS CSS-->
    <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/admin_style.css' %}"/>

    {#    Statistics #}
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css'
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
            integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
          integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous"/>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <style>
        #sidebar {
            background-color: #081828 !important;
        }

        .nav-link {
            padding: 20px;
        }

        .nav-link:hover {
            background-color: yellowgreen;
        }

        .nav-link:first-child:hover {
            background-color: #081828 !important;
            color: yellowgreen !important;
        }

        .nav-link a {
            color: #ffffff;
        }
    </style>
</head>
<body>
<!-- Side-Nav -->
<div class="side-navbar active-nav d-flex justify-content-between flex-wrap flex-column" id="sidebar">
    <ul class="nav flex-column text-white w-100 text-center">
        <a href="#" class="nav-link h3 text-white my-2">
            Auction BD
        </a>
        <p style="font-size: 15px; padding: 15px; margin-bottom: 100px;">{{ user }}</p>
        <li class="nav-link">
            <a href="{% url 'App_Admin:admin-dashboard' %}">
                <i class="fa fa-dashboard"></i>
                <span class="mx-2">Dashboard</span>
            </a>
        </li>
        <li class="nav-link">
            <a href="{% url 'App_Admin:products' %}">
                <i class="fa fa-bitcoin"></i>
                <span class="mx-2">Products</span>
            </a>
        </li>
        <li class="nav-link">
            <a href="{% url 'App_Admin:logout' %}">
                <i class="fa fa-sign-out"></i>
                <span class="mx-2">Logout</span>
            </a>
        </li>
    </ul>
</div>

<!-- Main Wrapper -->
<div class="p-1 my-container active-cont">
    <!-- Top Nav -->
    <nav class="navbar top-navbar px-5" style="background-color: #152B39!important">
        <a class="btn border-0" id="menu-btn"><i class="bx bx-menu"></i></a>
    </nav>

    {% block script %}
    {% endblock %}

    <!--End Top Nav -->
    {% block main %}
    {% endblock %}
</div>

<!-- bootstrap js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

<script>
    var menu_btn = document.querySelector("#menu-btn");
    var sidebar = document.querySelector("#sidebar");
    var container = document.querySelector(".my-container");
    menu_btn.addEventListener("click", () => {
        sidebar.classList.toggle("active-nav");
        container.classList.toggle("active-cont");
    });

</script>
</body>
</html>

templates/App_Admin/Test_dashboard.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css'
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
            integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
          integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous"/>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title></title>
</head>
<body>
{% block script %}

{% endblock %}
{% block main %}

{% endblock %}
</body>
</html>

templates/App_Admin/added_and_ended_auction_chart.html
{% extends 'App_Admin/Admin_base.html' %}
{% block script %}
    <script>
        $(document).ready(function () {
            const ctx = document.getElementById('myChart').getContext('2d');
            const myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in product %}"{{ i.created.day }}-{{ i.created.month }}-{{ i.created.year }}",{% endfor %}],
                    datasets: [{
                        label: '# of Votes Day',
                        data: [{% for i in product %} {{ i.auction_end_date.day }}, {% endfor %}],
                        backgroundColor: [
                            'rgba(133,15,41,0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 2
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        })
    </script>
{% endblock %}
{% block main %}
    <div>
        <canvas id="myChart" style="width: 200px;"></canvas>
    </div>
{% endblock %}

templates/App_Admin/added_ended_auction_chart_product.html
{% extends 'App_Admin/Admin_base.html' %}
{% load static %}
{% block title %}
    Running Auction
{% endblock %}
{% block main %}

    <style>
        /* Table Style Start */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        .legend {
            font-weight: 600;
            font-size: 19px;
            text-align: center;
            background-color: #2c3034;
            color: #ffffff;
            padding: 1.5rem;
            margin: 20px 0;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }

        /* Table Style End */
    </style>

    <div>
        <table>
            <legend class="legend">Statistic of Running Auction</legend>
            <thead>
            <tr>
                <th scope="col">Product Name</th>
                <th scope="col">Maximum Bidding Price</th>
                <th scope="col">Auction End Date</th>
            </tr>
            </thead>
            <tbody>
            {% for p in product %}
                <tr>
                    <td data-label="Product Name">
                        <a href="{% url 'App_Admin:added-ended-chart' pk=p.id %}">{{ p.product_name }}</a>
                    </td>
                    <td data-label="Maximum Bidding Price">{{ p.product_name }}</td>
                    <td data-label="Auction End Date">{{ p.auction_end_date }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/App_Admin/admin_dashboard.html
{% extends 'App_Admin/Admin_base.html' %}
{% block script %}
    <script>
        $(document).ready(function () {
            const ctx = document.getElementById('myChart').getContext('2d');
            const myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in product %}"{{ i.created.day }}",{% endfor %}],
                    datasets: [{
                        label: '# of Votes Day',
                        data: [{% for i in product %} {{ i.auction_end_date.day }}, {% endfor %}],
                        backgroundColor: [
                            'rgba(133,15,41,0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 2
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        })
    </script>
{% endblock %}
{% block main %}
    <style>
        body {
            overflow-y: scroll;
        }

        .card {
            margin: 10px;
        }

        .order-card {
            padding: 30px;
        }

        .card-data {
            float: right;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card bg-c-blue order-card">
                    <div class="card-block" style="cursor: pointer;"
                         onclick="window.location.href='{% url "App_Admin:running-auction" %}'">
                        <h6 class="m-b-20">STATISTICS OF AUCTION</h6>
                        <h2 class="text-right"><i class="fa fa-gavel f-left"></i></h2>
                        <p>
                            <a href="#" style="font-size: 20px;" class="card-data">
                                {{ product.count }}
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-c-blue order-card">
                    <div class="card-block" style="cursor: pointer;"
                         onclick="window.location.href='{% url "App_Admin:added-ended-chart-product" %}'"
                    >
                        <h6 class="m-b-20">TIME SERIES CHART OF AUCTION</h6>
                        <h2 class="text-right"><i class="fa fa-gavel f-left"></i></h2>
                        <p>
                            <a href="#" style="font-size: 20px;" class="card-data">
                                {{ product.count }}
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
    <div>
        <canvas id="myChart" style="width: 200px; display: none; overflow: scroll;"></canvas>
    </div>
    <script>
        let screenDay = document.getElementById('myChart');

        function showCanvas() {
            screenDay.style.display = 'block';
            screenHour.style.display = 'none';
            screenMin.style.display = 'none';
        }
    </script>
{% endblock %}

templates/App_Admin/running_auction.html
{% extends 'App_Admin/Admin_base.html' %}
{% load static %}
{% block title %}
    Running Auction
{% endblock %}
{% block main %}

    <style>
        /* Table Style Start */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        .legend {
            font-weight: 600;
            font-size: 19px;
            text-align: center;
            background-color: #2c3034;
            color: #ffffff;
            padding: 1.5rem;
            margin: 20px 0;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }

        /* Table Style End */
    </style>

    <div>
        <table>
            <legend class="legend">Statistic of Running Auction</legend>
            <thead>
            <tr>
                <th scope="col">Auction End Date</th>
                <th scope="col">Product Name</th>
                <th scope="col">Bidding Price Maximum</th>
                <th scope="col">Bidding Price Minimum</th>
                <th scope="col">Bidding Price Average</th>
            </tr>
            </thead>
            <tbody>
            {% for key, value in running_auction_stat %}
                <tr>
                    <td data-label="Auction End Date">
                        {% for i in running_auction %}
                            {% ifequal key i.id %}
                                {{ i.auction_end_date }}
                            {% endifequal %}
                        {% endfor %}
                    </td>
                    <td data-label="Product Name">
                        {% for i in running_auction %}
                            {% ifequal key i.id %}
                                <a href="{% url 'App_Admin:product-price-time-series' product_key=i.id %}">
                                    {{ i.product_name }}
                                </a>
                            {% endifequal %}
                        {% endfor %}
                    </td>
                    <td data-label="Bidding Price Maximum">{{ value.max }}</td>
                    <td data-label="Bidding Price Minimum">{{ value.min }}</td>
                    <td data-label="Bidding Price Average">{{ value.avg }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}