App_Admin/urls.py
from django.urls import path
from App_Admin import views

app_name = 'App_Admin'


urlpatterns = [
    path('', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-authentication/', views.admin_authentication_view, name='admin-authentication'),
    path('logout/', views.logout_view, name='logout'),
    path('products/', views.products_gallery, name='products'),
    path('running-auction/', views.running_auction, name='running-auction'),
    path('product-price-time-series/<product_key>/', views.product_price_time_series, name='product-price-time-series'),
    path('added-ended-chart-product/', views.added_ended_chart_product, name='added-ended-chart-product'),
    path('added-ended-chart/<pk>/', views.added_ended_chart, name='added-ended-chart'),
]

App_Auction/urls.py
from django.urls import path
from App_Auction import views

app_name = 'App_Auction'


urlpatterns = [
    path('product-details/<product_key>', views.product_details_view, name='product-details'),
    path('bid-request/', views.bid_start_view, name='bid-request'),
    path('user-participant-auction/', views.user_participant_auctions, name='user-participant-auction'),
    path('my-posted-auctions/', views.my_posted_auctions, name='my-posted-auctions'),
]

App_Authentication/urls.py
from django.urls import path
from App_Authentication import views
app_name = 'App_Authentication'


urlpatterns = [
    path('authentication/', views.authentication_view, name='authentication'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
]

Maloy_Auction_BD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import App_Auction.views

urlpatterns = [
    path('super-admin/', admin.site.urls),
    path('', App_Auction.views.home_view, name='home'),
    path('auction/', include('App_Auction.urls')),
    path('accounts/', include('App_Authentication.urls')),
    path('admin/', include('App_Admin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>Auction BD
    {% block title %}
    {% endblock %}
    </title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/logo.jpg' %}"/>

    <!-- ========================= CSS here ========================= -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/LineIcons.3.0.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/tiny-slider.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/glightbox.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        /* The submenu links container*/
        .subdrop {
            background: #1a5893;
            height: 0;
            border-top: 0;
            min-width: 100%;
            left: 0;
            margin: 0;
            position: absolute;
            text-align: left;
            top: 100%;
            visibility: hidden;
            height: 1px;
            overflow: hidden;
            z-index: 10;
        }

        /* Dropdown Parent Link Style */
        .droplink {
            display: inline-block;
            min-width: fit-content;
            position: relative;
        }

        .droplink a {
            color: #fff;
        }

        /* List elements within the dropdown */
        .subdrop li {
            display: block !important;
            padding: 0 !important;
        }

        /* Links within the dropdown list */
        .subdrop a {
            display: block;
            padding: 12px 20px;
            white-space: nowrap;
            color: white;
        }

        .subdrop a:hover {
            background: gold;
            color: #081828;
        }

        /* Allows links to show on hover/focus and through keyboard navigation via focus-within */
        .droplink:hover .subdrop {
            visibility: visible;
            height: auto;
            z-index: 11;
        }

        /* Separate these to avoid IE completely ignoring the css above */
        .droplink:focus-within .subdrop {
            visibility: visible;
            height: auto;
            z-index: 11;
        }
    </style>

</head>

<body>
<!-- Preloader -->
<div class="preloader">
    <div class="preloader-inner">
        <div class="preloader-icon">
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<!-- /End Preloader -->

<!-- Start Header Area -->
<header class="header navbar-area">
    <!-- Start Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4 text-center">
                    <!-- Start Header Logo -->
                    <a class="navbar-brand" href="{% url 'home' %}">
                        Auction BD
                    </a>
                    <!-- End Header Logo -->
                </div>
                <div class="col-md-4">
                    <div class="top-middle">
                        <ul class="useful-links">
                            <li><a href="{% url 'home' %}">Home</a></li>
                            <li><a target="_blank" href="https://www.linkedin.com/in/maloy-baroi-745915163/">About Us</a></li>
                            <li><a target="_blank" href="https://mail.google.com/mail/u/1/#inbox?compose=VpCqJWHlhLhjvCrFPZxQsCSrXxGHWkncBWxgPswPsFvsjrsvcVpRhCQJCLHpHDGwJdNZgng">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12">
                    <div class="top-end">
                        <div class="user">
                            <i class="lni lni-user"></i>
                            {% if user.is_authenticated %}
                                <li class="droplink"><i class="fa fa-angle-double-down">{{ user|truncatechars:5 }}</i>
                                    <ul class="subdrop" aria-label="Main Links Sub Navigation">
                                        <li><a href="{% url 'App_Auction:my-posted-auctions' %}">My posted items</a></li>
                                        <li><a href="{% url 'App_Authentication:profile' %}">Profile Settings</a></li>
                                        <li><a href="{% url 'App_Authentication:logout' %}">Logout</a></li>
                                    </ul>
                                </li>
                            {% else %}
                                Hello
                            {% endif %}
                        </div>
                        {% if user.is_authenticated %}
                            <ul class="user-login">
                                <li>
                                    <a href="{% url 'App_Auction:user-participant-auction' %}">
                                        <i class="fa fa-shopping-bag"> View My Bids</i>
                                    </a>
                                </li>
                            </ul>
                        {% else %}
                            <ul class="user-login">
                                <li>
                                    <a href="{% url 'App_Authentication:authentication' %}">Register</a>
                                </li>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
</header>
<!-- End Header Area -->

{% block main %}
{% endblock %}



<!-- ========================= scroll-top ========================= -->
<a href="#" class="scroll-top">
    <i class="lni lni-chevron-up"></i>
</a>

<!-- ========================= JS here ========================= -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/tiny-slider.js' %}"></script>
<script src="{% static 'assets/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script type="text/javascript">
    //========= Hero Slider
    tns({
        container: '.hero-slider',
        slideBy: 'page',
        autoplay: true,
        autoplayButtonOutput: false,
        mouseDrag: true,
        gutter: 0,
        items: 1,
        nav: false,
        controls: true,
        controlsText: ['<i class="lni lni-chevron-left"></i>', '<i class="lni lni-chevron-right"></i>'],
    });

    //======== Brand Slider
    tns({
        container: '.brands-logo-carousel',
        autoplay: true,
        autoplayButtonOutput: false,
        mouseDrag: true,
        gutter: 15,
        nav: false,
        controls: false,
        responsive: {
            0: {
                items: 1,
            },
            540: {
                items: 3,
            },
            768: {
                items: 5,
            },
            992: {
                items: 6,
            }
        }
    });
</script>
</body>

</html>

templates/home.html
{% extends 'Base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Home
{% endblock %}
{% block main %}
    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
            width: 80%;
            padding: 20px;
            margin: 5px;
            height: 464px;
        }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
        }

        del {
            color: red;
        }

        label {
            color: #008811;
            text-decoration: black !important;
            float: left !important;
        }

        .form-group {
            margin: 20px 0 !important;
        }

    </style>

    <div class="container text-center" style="background-color: #0818">
        <!-- Button trigger modal -->
        <a class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="fa fa-plus-circle ml-2 mr-2" style="color: #ffffff; padding: 15px;">Add a Auction</i>
        </a>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-body">
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Start Auction</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row">
            {% for product in products %}
                <div class="col-md-4">
                    <div class="card">
                        <a href="" data-bs-toggle="modal" data-bs-target="#exampleModalPhoto{{ product.id }}">
                            <img src="{{ product.product_photo.url }}" alt="Product Image"
                                 style="width:100%; height: 300px">
                        </a>
                        <div class="container">
                            <h6><b>{{ product.product_name }}</b></h6>
                            <p>
                                {% if product.selling_price %}
                                    <del>{{ product.minimum_bid_price }}</del>
                                    <span>
                                    {{ product.selling_price }}
                                    </span>
                                {% else %}
                                    <span>{{ product.minimum_bid_price }}</span>
                                    <del>{{ product.selling_price }}</del>
                                {% endif %}
                            </p>
                            <a href="{% url 'App_Auction:product-details' product_key=product.id %}" type="button"
                               class="btn" style="background-color: #081828; color: #ffffff">
                                View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}